name: BasicSample

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/BasicSample.yaml'
      - 'BasicSample/**'
  pull_request:
    paths:
      - '.github/workflows/BasicSample.yaml'
      - 'BasicSample/**'

env:
  SAMPLE_PATH: BasicSample

jobs:
  build_and_test:
    runs-on: macOS-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: java
          queries: +security-and-quality        

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Build project
        working-directory: ${{ env.SAMPLE_PATH }}
        run: ./gradlew assembleDebug lintDebug --stacktrace
        
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2        
